apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: skywalking
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: "elasticsearch-9200"
    - protocol: TCP
      port: 9300
      targetPort: 9300
      name: "elasticsearch-9300"
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-server
  namespace: skywalking
spec:
  selector:
    app: skywalking-server
  ports:
    - protocol: TCP
      port: 12800
      targetPort: 12800
      name: "skywalking-server-12800"
    - protocol: TCP
      port: 11800
      targetPort: 11800
      name: "skywalking-server-11800"
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  namespace: skywalking
spec:
  selector:
    app: skywalking-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort